### ISSUE TITLE
npm run dev项目访问  404未找到

### ISSUE THREAD

**Issue by tangyuhui** [microzz/vue-music-player#11]
GET http://localhost:8080/ 404 (Not Found)
用 npm install 安装了依赖，但通过npm run dev时浏览器报错。404未找到

**Comment by microzz** [comment]
@tangyuhui node升级到新版本后，请确认cd到了项目目录并且依赖都已正确安装，国内可以尝试cnpm。

**Comment by tangyuhui** [comment]
解决了，node-sass没有正确安装。 换cnpm重装了一次。项目能运行了。谢谢~

**Comment by tangyuhui** [comment]
解决了，node-sass没有正确安装。 换cnpm重装了一次。项目能运行了。谢谢~
