### ISSUE TITLE
音乐播放显示 NaN:NaN （附图）| 解决办法？

### ISSUE THREAD

**Issue by hanyucd** [microzz/vue-music-player#17]
请问音乐播放区域狂跳转，怎么解决呀？
如图（gif图片）：

![image](https://user-images.githubusercontent.com/13725830/34903476-350db004-f86d-11e7-829f-06b6872e8229.gif)

**Comment by microzz** [comment]
@hanyucd 默认歌曲列表里面的歌曲链接失效了，替换即可

**Comment by hanyucd** [comment]
@microzz 
替换哪里的链接，详讲下？

**Comment by microzz** [comment]
@hanyucd https://github.com/microzz/vue-music-player/blob/2.0.0/music-data.json

**Comment by hanyucd** [comment]
@microzz  懂了，你是说把这个 json 里的 mp3 链接替换为其他的？

**Comment by hanyucd** [comment]
我问下，怎么才能找到像 网易云、QQ音乐、等这些音乐站点的 Api 呢？

**Comment by microzz** [comment]
@hanyucd 网上找或者抓包

**Comment by xiaoshidetaikuai** [comment]
为什么我改了music-data.json还是会有之前的音乐列表呢？我全删掉音乐还是存在

**Comment by microzz** [comment]
@xiaoshidetaikuai 清空localStorage。现在该项目已经不维护了，更多的需要你自己去探索了~

**Comment by xiaoshidetaikuai** [comment]
谢谢
