### ISSUE TITLE
为什么你的项目运行起来在我的chrome下vue-devtool没有出来，其他的用vue-cli创建的项目有vue-devtool

### ISSUE THREAD

**Issue by saint3347** [microzz/vue-music-player#5]
![image](https://cloud.githubusercontent.com/assets/7347133/24958953/b10ddd06-1fc3-11e7-9f5e-56ccba17af78.png)

**Comment by saint3347** [comment]
是我本地启动的，http://localhost:8080/#/

**Comment by microzz** [comment]
@saint3347 你好，我的npm run dev是可以正常使用Vue的调试工具，现在解决了吗？
